### ISSUE TITLE
Support GitHub Enterprise

### ISSUE THREAD

**Issue by ponkio-o** [suzuki-shunsuke/release-js-action#108]
Hello @suzuki-shunsuke. Thank you for developing such a wonderful tool.

We are using GitHub Enterprise Server (GHES) and would like to utilize this Action on GHES. For this, we need to modify the settings of some tools used by this Action.

- cli/cli (gh)
- int128/ghcp

For int128/ghcp, it is necessary to set `GITHUB_API`.
https://github.com/int128/ghcp#github-enterprise

For cli/cli, we need to set two environment variables: `GH_HOST` and `GH_ENTERPRISE_TOKEN`. It's possible for `GH_ENTERPRISE_TOKEN` to coexist with `GH_TOKEN`.

By making changes like those in the PR below, it worked correctly.
https://github.com/ponkio-o/release-js-action/pull/1

```yaml
name: Update the latest branch
on:
  push:
    branches:
      - main
jobs:
  build:
    timeout-minutes: 15
    runs-on:
      group: enterprise
      labels: small
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run build
      - uses: ponkio-o/release-js-action@pr/1
        with:
          version: latest
        env:
          GITHUB_API: https://github.example.jp/api/v3/
          GH_HOST: github.example.jp
```

However, this approach might cause confusion since the environment variables are set even when not using GHES. Alternatively, introducing a new input flag (like `use_enterprise`) and writing `GH_ENTERPRISE_TOKEN` to `GITHUB_ENV` in the initial step is another option.

Do you have any better solutions? If there's no issue with the changes above, I will proceed to create a new PR.

**Comment by suzuki-shunsuke** [comment]
> However, this approach might cause confusion since the environment variables are set even when not using GHES.

What does it mean?
Whether the repository is GHES or not is clear.
Are you concern that workflows for GHES are copied and pasted to non GHES repositories?

**Comment by suzuki-shunsuke** [comment]
Ah, I see.
Your pr fixes the composite action.
https://github.com/ponkio-o/release-js-action/pull/1/files

How about this?

```yaml
- uses: ponkio-o/release-js-action@pr/1
        with:
          version: latest
        env:
          GITHUB_API: https://github.example.jp/api/v3/
          GH_HOST: github.example.jp
          GH_ENTERPRISE_TOKEN: ${{github.token}}
```
